
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - carp.juan-lee.dev
  resources:
  - workers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - carp.juan-lee.dev
  resources:
  - workers/status
  verbs:
  - get
  - patch
  - update
